### ISSUE TITLE
An exception is thrown if no save file is found

### ISSUE THREAD

**Issue by JudgeZarbi** [JudgeZarbi/smb2-team-transfer-tool#27]
```
Ferrea's SMB2 Team Transfer Tool 0.1 beta
No save data found.
Press Enter to exit.

Traceback (most recent call last):
  File "main.py", line 381, in <module>
  File "main.py", line 329, in main
  File "util/save.py", line 38, in load_data
UnboundLocalError: local variable 'in_file' referenced before assignment
[26677] Failed to execute script main
```

It should never happen, but this needs to be fixed anyway.

**Comment by JudgeZarbi** [comment]
Turns out this was fixed accidentally in the code refactor.
