### ISSUE TITLE
Tool can potentially crash while creating team packs

### ISSUE THREAD

**Issue by JudgeZarbi** [JudgeZarbi/smb2-team-transfer-tool#40]
Test case and more information coming soon.

**Comment by JudgeZarbi** [comment]
Error:

```
Page 2 of team files
Choose an option.
0. Danganronpa_9.team
1. Midgar_Avalanche.team
2. Third_Street_Saints.team
p. Previous page
d. Done
--> 0

Page 2 of team files
Choose an option.
0. Midgar_Avalanche.team
1. Third_Street_Saints.team
p. Previous page
d. Done
--> 0

Page 2 of team files
Choose an option.
0. Third_Street_Saints.team
p. Previous page
d. Done
--> 0

Page 2 of team files
Choose an option.
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "main.py", line 30, in main
  File "exports/pack.py", line 29, in create_team_pack
  File "exports/pack.py", line 15, in _get_team_files
  File "util/file/common.py", line 68, in select_file
IndexError: list index out of range
[30013] Failed to execute script main
```
