### ISSUE TITLE
Error importing logos

### ISSUE THREAD

**Issue by JudgeZarbi** [JudgeZarbi/smb2-team-transfer-tool#53]
An error message is displayed, but I don't have it right now. Reported by OpusSMB2 on Discord.

**Comment by JudgeZarbi** [comment]
Page 1 of team files
Choose an option.
0. exports.logo
b. Go back
--> 0
Type the name of the team you wish to import the logo to.
--> logotest
Found a team! Using found team.
Traceback (most recent call last):
  File "main.py", line 59, in <module>
  File "main.py", line 39, in main
  File "imports\logo.py", line 49, in import_logo
  File "util\file\common.py", line 195, in import_file
  File "util\file\logo.py", line 38, in import_logo
NameError: name 'uuid' is not defined
[95788] Failed to execute script main
